"""
Use Gemini to generate a final feedback response from extract_proposal.py output.

Two modes:
1) Read precomputed analysis JSON:
   python commentaire.py --analysis-json /path/to/analysis.json

2) Run extraction + analysis first, then summarize:
   python commentaire.py --proposal-pdf /path/to/proposal.pdf
"""

from __future__ import annotations

import argparse
import json
import os
from typing import Any, Dict

from extract_proposal import analyze_uploaded_pdf

try:
    import google.generativeai as genai
except ImportError as exc:
    raise ImportError(
        "Missing dependency google-generativeai. Install with: pip install google-generativeai"
    ) from exc

GEMINI_MODEL_DEFAULT = "gemini-2.5-flash-lite"
_GEMINI_API_ENDPOINT = "generativelanguage.googleapis.com"


def _gemini_api_key() -> str:
    raw = str(os.environ.get("GEMINI_API_KEY", "") or "").strip()
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in "\"'":
        raw = raw[1:-1].strip()
    if not raw:
        raise EnvironmentError("GEMINI_API_KEY is not set in environment.")
    return raw


def _configure_gemini() -> None:
    from google.api_core.client_options import ClientOptions

    genai.configure(
        api_key=_gemini_api_key(),
        client_options=ClientOptions(api_endpoint=_GEMINI_API_ENDPOINT),
    )


def _load_analysis_from_json(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as file:
        data = json.load(file)
    if not isinstance(data, dict):
        raise ValueError("Analysis JSON must contain an object/dictionary.")
    return data


def _build_gemini_prompt(analysis: Dict[str, Any]) -> str:
    return f"""
You are a startup proposal reviewer.
Create a clear, practical feedback report for the founder using this analysis JSON.

Requirements:
- Keep it concise and actionable.
- Include sections:
  1) Overall Verdict
  2) Filled Criteria (strengths)
  3) Missing/Partial Criteria (gaps)
  4) Common Startup Failure Risks Found
  5) Top 5 Next Actions (prioritized)
- Use plain English.
- If some fields are missing, handle gracefully.

Analysis JSON:
{json.dumps(analysis, indent=2)}
"""


def generate_commentary_with_gemini(
    analysis: Dict[str, Any],
    model_name: str = GEMINI_MODEL_DEFAULT,
) -> str:
    _configure_gemini()
    model = genai.GenerativeModel(model_name)

    prompt = _build_gemini_prompt(analysis)
    response = model.generate_content(prompt)
    text = getattr(response, "text", None)
    if not text:
        raise RuntimeError("Gemini returned an empty response.")
    return text.strip()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Gemini feedback from extract_proposal.py results."
    )
    parser.add_argument(
        "--analysis-json",
        default="",
        help="Path to analysis JSON previously generated by extract_proposal.py",
    )
    parser.add_argument(
        "--proposal-pdf",
        default="",
        help="If provided, run analyze_uploaded_pdf on this PDF before Gemini summary.",
    )
    parser.add_argument(
        "--criteria-pdf",
        default="RAG-layer-of-startup-judging/criteria_evaluate.pdf",
        help="Path to criteria PDF source.",
    )
    parser.add_argument(
        "--startup-pdf",
        default="RAG-layer-of-startup-judging/startup_failure_reason.pdf",
        help="Path to startup failure reasons PDF source.",
    )
    parser.add_argument(
        "--model",
        default=GEMINI_MODEL_DEFAULT,
        help=f"Gemini model name (default: {GEMINI_MODEL_DEFAULT}).",
    )
    parser.add_argument(
        "--save-output",
        default="",
        help="Optional path to save Gemini commentary as .txt/.md.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if args.analysis_json:
        analysis = _load_analysis_from_json(args.analysis_json)
    elif args.proposal_pdf:
        analysis = analyze_uploaded_pdf(
            proposal_pdf=args.proposal_pdf,
            criteria_pdf=args.criteria_pdf,
            startup_pdf=args.startup_pdf,
        )
    else:
        raise ValueError("Provide either --analysis-json or --proposal-pdf.")

    commentary = generate_commentary_with_gemini(analysis, model_name=args.model)
    print(commentary)

    if args.save_output:
        with open(args.save_output, "w", encoding="utf-8") as file:
            file.write(commentary + "\n")
        print(f"\nSaved Gemini commentary to: {args.save_output}")


if __name__ == "__main__":
    main()
